FLAGS += -Xiwyu --no_fwd_decls
FLAGS += -w  # disable compiler warnings
FLAGS += $(shell cat compile_flags.txt)

# skip my weird glob implementation, too dynamic or something
SRC := $(wildcard src/*.cpp src/*.hpp)

all: $(SRC)

.PHONY: $(SRC)
$(SRC):
	((iwyu $(FLAGS) $@ || true) 2>&1) | sed '/has correct #includes/d' | (! grep .)
